### ISSUE TITLE
How to use this for other file type.

### ISSUE THREAD

**Issue by fuyunzhishang** [JSila/atom-self-closing-tag#1]
I want to know how to use this for other file type. like *.vue . Thanks.

**Comment by JSila** [comment]
At this moment, only html and jsx scopes are supported (each file type has an associated scope). When I developed it, I set only them because that's where I needed this functionality.

What file types do you want this plugin to support besides *.vue? It would be great if you also tell what scopes have these file types (because maybe I don't use them). [Here's a guide](https://discuss.atom.io/t/get-scope-for-theming/11581) how to find scope for a file.

**Comment by fuyunzhishang** [comment]
Thanks a lot, that's might be great help!
